### ISSUE TITLE
The task mangles Utf8 into unrecognizable characters.

### ISSUE THREAD

**Issue by Zazcallabah** [knom/vsts-markdown-tasks#13]
When I try to use this task to render the following markdown

    # Testing “quotes”.

saved with utf8 encoding.

The resulting file contains this:

    <h1>Testing ΓÇ£quotesΓÇ¥.</h1>

which obviously isnt good. Is this a vsts issue, or a specific issue with this task?

**Comment by knom** [comment]
# Testing “quotes”.

**Comment by knom** [comment]
Okay.. Github does a better job..

**Comment by knom** [comment]
Testing the underlying library here https://markdown-it.github.io it seems to work..

I think it might be somewhere in the task code itself..

**Comment by Zazcallabah** [comment]
I imagine it could also be depending on the cli used by the task agent.

**Comment by knom** [comment]
@Zazcallabah: I've just created a Test Case for this as well...
(See PR #14 ) 

And it just works fine.. :-(

So the question is.. WHERE is the issue..

Can you turn "System.Debug" = true on in the BUILD - and run it again - and post the output here, please?

**Comment by Zazcallabah** [comment]
Wait a minute, I think I've made a mistake. I thought the task placed the generated files beside the markdown files, but it seems to place them in the working directory. So the files I looked at and saw mangled utf8 were files from other processes.

I'm sorry to have wasted your time. When I look at the correct files, they handle utf8 as they should. Thank you for your help.

Is there any way to get the behavior I want, where the generated files are placed in the same folder as their markdown source?

**Comment by knom** [comment]
Just leave the output directory empty.. It should just use the directory of the .MD file..

**Comment by Zazcallabah** [comment]
That's what I did. That seems to place all the files in the working directory.

> 2018-10-25T09:10:17.5511518Z Successfully transformed 7 markdown files to HTML files: 
> 2018-10-25T09:10:17.5511757Z D:\a\1\s\Vision\Automation\Automation.md ==> D:\a\1\s\Automation.html
> 2018-10-25T09:10:17.5511951Z D:\a\1\s\Vision\Frontend\Frontend.md ==> D:\a\1\s\Frontend.html
> 2018-10-25T09:10:17.5512113Z D:\a\1\s\Vision\Security\Security.md ==> D:\a\1\s\Security.html
> 2018-10-25T09:10:17.5512363Z D:\a\1\s\Vision\ServiceDesign\ServiceDesign.md ==> D:\a\1\s\ServiceDesign.html
> 2018-10-25T09:10:17.5512546Z D:\a\1\s\Vision\TargetArchitecture.md ==> D:\a\1\s\TargetArchitecture.html
> 2018-10-25T09:10:17.5512790Z D:\a\1\s\Vision\index.md ==> D:\a\1\s\index.html
> 2018-10-25T09:10:17.5512974Z D:\a\1\s\Vision\servicedesignvision.md ==> D:\a\1\s\servicedesignvision.html

This is what caused the confusion in the first place. :)
