### ISSUE TITLE
Add support for markdown-it-anchor's legacy slugify behavior

### ISSUE THREAD

**Issue by HolisticDeveloper** [knom/vsts-markdown-tasks#15]
I use the [Markdown All in One](https://github.com/yzhang-gh/vscode-markdown) extension for VS Code to generate a table of contents in my markdown files. It expects that anchors will be added for each header using a specific format. However, the mechanism for creating the "slugs" differs in that extension from this one.

This extension makes use of [markdown-it-anchor](https://github.com/valeriangalliat/markdown-it-anchor). Their readme describes how to get similar anchors by substituting their slugify function for the one contained in the npm `string` package:

```js
const string = require('string')
const legacySlugify = s => string(s).slugify().toString()

const md = require('markdown-it')()
const anchor = require('markdown-it-anchor', {
	slugify: legacySlugify
})
```

An option to be able to use that legacy behavior would be beneficial.

**Comment by HolisticDeveloper** [comment]
I am planning to submit a PR for this shortly.

**Comment by knom** [comment]
Great! I will review and publish to Marketplace once it is in!

Thanks for your contribution.

Should this be an OPTION or just be the default?
What would be the downside of legacySlugify?

Thx.
