### ISSUE TITLE
yaml build

### ISSUE THREAD

**Issue by morten-nielsen** [knom/vsts-markdown-tasks#19]
Does this task support yaml pipeline, I get this error "String does not match the pattern of "^PowerShell@2$"."

**Comment by knom** [comment]
Can you post the entire YAML pipeline?
It should in *GENERAL* support it, but maybe there's a bug..

**Comment by morten-nielsen** [comment]
This issue is resolved, or I cannot reproduce it. Task works as expected in yaml pipeline.
