### ISSUE TITLE
Anchors are not created for headers

### ISSUE THREAD

**Issue by randomnote1** [knom/vsts-markdown-tasks#2]
Markdown automatically creates an anchor for each heading (e.g. `## Heading2`) which can be linked to anywhere else in the document (e.g. `[Link to Heading](#heading2)`). Markdown 2 HTML should create anchors along with the appropriate heading to maintain this support. For example, the following markdown would generate the following HTML:

Markdown:
```markdown
# Title

## Table of Contents

- [Section 1](#section-1)
- [Section 2](#section-2)

## Section 1

## Section 2

```

HTML:
```html
<html>
<head></head>
<body>
    <a name="title"></a><h1>Title</h1>
    <a name="table-of-contents"></a><h2>Table of Contents</h2>
    <ul>
        <li><a href="#section-1">Section 1</a></li>
        <li><a href="#section-2">Section 2</a></li>
    </ul>
    <a name="section-1"></a><h2>Section 1</h2>
    <a name="section-2"></a><h2>Section 2</h2>
</body>
</html>
```

**Comment by knom** [comment]
Thanks for submitting the request!
I'm using MARKDOWN-IT to do the transformation..

Any markdown-it plugin could be enabled..

Is THAT one doing what you propose?
https://www.npmjs.com/package/markdown-it-anchor

**Comment by randomnote1** [comment]
Yup, it looks like that will do the trick.  Here's what I used to [Try it out](https://npm.runkit.com/markdown-it-anchor).

```javascript
const md = require('markdown-it')()
const anchor = require('markdown-it-anchor')

md.use(anchor, {
  level: 1,
  // slugify: string => string,
  permalink: false,
  // renderPermalink: (slug, opts, state, permalink) => {},
  permalinkClass: 'header-anchor',
  permalinkSymbol: '¶',
  permalinkBefore: false
})

const src = `
# Title

## Table of Contents

- [Section 1](#section-1)
- [Section 2](#section-2)

## Section 1

## Section 2
`

console.log(md.render(src))
```

**Comment by knom** [comment]
Thanks @randomnote1 !
Would you mind doing a pull request?

Thanks, max.

**Comment by randomnote1** [comment]
I'll give it a try. I have no idea how to test this in the real world!

**Comment by knom** [comment]
Thanks! Looks good to me!
I will roll-out an update to the marketplace soon..

**Comment by randomnote1** [comment]
Cool! Looking forward to seeing it.

When you roll it out, will my build automation automatically pick up the update?

**Comment by knom** [comment]
Not sure.. You might want to re-install..

**Comment by randomnote1** [comment]
Sounds good. I'll report back after the update is rolled out.

**Comment by knom** [comment]
Try the latest version 2.1.8 from marketplace, which should have it in..

Thanks!

**Comment by randomnote1** [comment]
It works! The Markdown2Html plugin is selected as 2.*, so it automatically picked it up.

**Comment by knom** [comment]
Great!
