### ISSUE TITLE
MD link target

### ISSUE THREAD

**Issue by kine** [knom/vsts-markdown-tasks#20]
Hi,
is there some possibility to autotranslate the link to .md file to .html in the generated html?

when I use

`[Some link to another page](Page1.md)`

The result in HTML leads to Page1.md instead Page1.html.

Thanks.

**Comment by knom** [comment]
Interesting.. let me investigate..

**Comment by kine** [comment]
Seems related to https://github.com/markdown-it/markdown-it/issues/548

**Comment by knom** [comment]
Do you want to craft a Pull Request following this example...?
https://github.com/markdown-it/markdown-it/issues/548#issuecomment-623078580

thx.

**Comment by kine** [comment]
No, sorry, this is outside my expertise. Right now we changed the technology and we are using MkDocs.

**Comment by knom** [comment]
Here's my first draft...
#22

**Comment by knom** [comment]
@kine 
This is fixed in PR #22 .
And released as version 3.0.3 to the marketplace.

Feel free to use it - and let me know how it works!
