### ISSUE TITLE
Inline html is converted to text

### ISSUE THREAD

**Issue by SWarnberg** [knom/vsts-markdown-tasks#4]
Many fields in TFS are of type html. Hence, the markdown exported with the GenerateReleaseNotes task contains inline html, like the following example:

`| ID | Comment |
| --- | --- |
| 345 | <div>a comment with <b>bold</b></div>
`

However, this task converts all html to text, like `&lt;div&gt;`, which breaks the formatting of those fields.

**Comment by knom** [comment]
Oh.. Looking at the underlying library markdown - it, there's a way to suppress the html escaping..
Let me fix this..

**Comment by knom** [comment]
Just published version 2.3.0 into the marketplace.
Please install - it does support Inline HTML passthrough now!
