### ISSUE TITLE
Source and destination paths should support wildcards

### ISSUE THREAD

**Issue by randomnote1** [knom/vsts-markdown-tasks#5]
The `Markdown file path` and `HTML output file path` should support wildcards so multiple Markdown files can be converted in one agent step.

**Comment by knom** [comment]
Looking at this https://github.com/Microsoft/vsts-task-lib/blob/master/node/docs/findingfiles.md..
The change might be more complex..

- A different UI (directory textbox + matching pattern textbox)
- A find() call
- Maybe a switch between "transform a single file" and "transform multiple files"
    So that the old UI and the new UI can co-exist.

What do you think?

**Comment by randomnote1** [comment]
After thinking about this and looking at some other tasks, I think using a directory textbox plus a matching pattern textbox would be the best option. This would be similar to the [Publish Test Results](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results) task. I believe this will accommodate documentation stored in multiple locations throughout the project a little more easily.

To accommodate the interface change, I think this could be considered version 3.0. I think this will populate the `Version` dropdown menu on the build task screen.

**Comment by knom** [comment]
Sounds great!
I suppose on the output file paths these would just be the same as input.
As well as the filenames. 

A copy file task could then move them to a central place if needed.. 

Do you want to go ahead and start coding this?

**Comment by randomnote1** [comment]
Yes, I think it's safe to assume (for the time being) the output location and filenames would be the same as the input.

Yeah, if you have the bandwidth!

**Comment by knom** [comment]
I'm just fixing another issue.. Appreciated, if you could give it a try ;-)

**Comment by randomnote1** [comment]
Sure! Is it published to VSTS (I mean ADO)? If not, how do I test?

**Comment by knom** [comment]
Ah no ;-) I mean "try start implementing it" :-)
I haven't written anything yet.. But worked on another feature..

**Comment by knom** [comment]
This is live now - in 3.0.2.
